# Generated by Django 4.2.24 on 2025-09-27 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='databundle',
            name='validity_days',
        ),
        migrations.RemoveField(
            model_name='routerproduct',
            name='features',
        ),
        migrations.AddField(
            model_name='databundle',
            name='data_amount',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='databundle',
            name='validity',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='routerproduct',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='routers/'),
        ),
        migrations.AddField(
            model_name='routerproduct',
            name='specifications',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='databundle',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='databundle',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='databundle',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bundles', to='store.serviceprovider'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='order',
            name='service_type',
            field=models.CharField(choices=[('bundle', 'Data Bundle'), ('router', 'Router')], max_length=50),
        ),
        migrations.AlterField(
            model_name='routerproduct',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='routerproduct',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='color',
            field=models.CharField(default='#000000', max_length=7),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='providers/'),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
