# Generated by Django 4.2.24 on 2025-10-04 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='databundle',
            name='description',
        ),
        migrations.RemoveField(
            model_name='databundle',
            name='validity',
        ),
        migrations.RemoveField(
            model_name='order',
            name='additional_notes',
        ),
        migrations.RemoveField(
            model_name='order',
            name='email',
        ),
        migrations.RemoveField(
            model_name='order',
            name='package_details',
        ),
        migrations.RemoveField(
            model_name='order',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='order',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='routerproduct',
            name='description',
        ),
        migrations.RemoveField(
            model_name='routerproduct',
            name='image',
        ),
        migrations.RemoveField(
            model_name='routerproduct',
            name='specifications',
        ),
        migrations.RemoveField(
            model_name='serviceprovider',
            name='color',
        ),
        migrations.RemoveField(
            model_name='serviceprovider',
            name='description',
        ),
        migrations.RemoveField(
            model_name='serviceprovider',
            name='logo',
        ),
        migrations.AlterField(
            model_name='databundle',
            name='data_amount',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='databundle',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='databundle',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.serviceprovider'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='service_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='routerproduct',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
