# Generated by Django 4.2.24 on 2025-10-15 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_databundle_description_databundle_validity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='routerproduct',
            name='color',
            field=models.CharField(default='#000000', max_length=7),
        ),
    ]
