# Generated by Django 4.2.24 on 2025-10-15 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_routerproduct_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routerproduct',
            name='color',
            field=models.CharField(max_length=7),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='color',
            field=models.CharField(max_length=7),
        ),
    ]
