# Generated by Django 4.2.7 on 2025-11-13 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_routerproduct_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routerproduct',
            name='color',
            field=models.CharField(default='#000000', max_length=7),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='color',
            field=models.CharField(default='#000000', max_length=7),
        ),
    ]
