# Generated by Django 4.2.7 on 2025-11-15 07:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0006_alter_routerproduct_color_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='serviceprovider',
            options={'verbose_name': 'Service Provider', 'verbose_name_plural': 'Service Providers'},
        ),
        migrations.RenameField(
            model_name='order',
            old_name='email',
            new_name='customer_email',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='phone',
            new_name='customer_phone',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='additional_notes',
            new_name='notes',
        ),
        migrations.RemoveField(
            model_name='databundle',
            name='data_amount',
        ),
        migrations.RemoveField(
            model_name='databundle',
            name='validity',
        ),
        migrations.RemoveField(
            model_name='order',
            name='package_details',
        ),
        migrations.RemoveField(
            model_name='order',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='service_type',
        ),
        migrations.RemoveField(
            model_name='routerproduct',
            name='color',
        ),
        migrations.RemoveField(
            model_name='routerproduct',
            name='image',
        ),
        migrations.RemoveField(
            model_name='serviceprovider',
            name='color',
        ),
        migrations.RemoveField(
            model_name='serviceprovider',
            name='logo',
        ),
        migrations.AddField(
            model_name='databundle',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='databundle',
            name='data_volume',
            field=models.CharField(default='1GB', max_length=50),
        ),
        migrations.AddField(
            model_name='databundle',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='databundle',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='databundle',
            name='validity_days',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='order',
            name='admin_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='product_details',
            field=models.TextField(default='No details provided'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='routerproduct',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='routerproduct',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='routerproduct',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='contact_email',
            field=models.EmailField(default='frechaiotech@gmail.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='databundle',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='databundle',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='routerproduct',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='routerproduct',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
