# Generated by Django 4.2.7 on 2025-11-15 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_order_options_alter_serviceprovider_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceprovider',
            name='contact_email',
        ),
        migrations.RemoveField(
            model_name='serviceprovider',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='serviceprovider',
            name='website',
        ),
    ]
