# Generated by Django 4.2.7 on 2025-11-16 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_remove_serviceprovider_contact_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='routerproduct',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='routers/'),
        ),
    ]
