# Generated by Django 4.2.7 on 2025-11-16 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_routerproduct_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at'], 'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
        migrations.AddField(
            model_name='order',
            name='customer_notified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='notification_method',
            field=models.CharField(blank=True, choices=[('email', 'Email'), ('sms', 'SMS'), ('both', 'Both')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='notification_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='service_type',
            field=models.CharField(choices=[('bundle', 'Data Bundle'), ('router', 'Router Product')], default='bundle', max_length=20),
        ),
    ]
