# Generated by Django 4.2.7 on 2025-11-16 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_electronicsdevices'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ElectronicsDevices',
            new_name='Electronics',
        ),
    ]
