# Generated by Django 5.2.8 on 2025-11-16 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_rename_electronicsdevices_electronics'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Electronics',
            new_name='ElectronicsDevices',
        ),
    ]
