# Generated by Django 5.2.8 on 2025-11-16 23:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_rename_electronics_electronicsdevices'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='electronicsdevices',
            options={'ordering': ['-created_at'], 'verbose_name': 'Electronics Device', 'verbose_name_plural': 'Electronics Devices'},
        ),
        migrations.AddField(
            model_name='electronicsdevices',
            name='category',
            field=models.CharField(choices=[('laptops', 'Laptops'), ('smartphones', 'Smartphones'), ('tablets', 'Tablets'), ('accessories', 'Accessories'), ('gaming', 'Gaming Consoles'), ('audio', 'Audio Equipment'), ('cameras', 'Cameras'), ('networking', 'Networking Devices'), ('storage', 'Storage Devices'), ('other', 'Other Electronics')], default='other', max_length=50),
        ),
        migrations.AddField(
            model_name='electronicsdevices',
            name='stock_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='electronics_device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.electronicsdevices'),
        ),
        migrations.AddField(
            model_name='order',
            name='router_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.routerproduct'),
        ),
        migrations.AlterField(
            model_name='order',
            name='service_type',
            field=models.CharField(choices=[('data_plan', 'Data Plan'), ('bundle', 'Bundle Package'), ('router', 'Router Product'), ('electronics', 'Electronics Device')], default='data_plan', max_length=20),
        ),
        migrations.CreateModel(
            name='Bundle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('bundle_type', models.CharField(choices=[('individual', 'Individual Bundle'), ('family', 'Family Bundle'), ('business', 'Business Bundle'), ('student', 'Student Bundle'), ('premium', 'Premium Bundle')], default='individual', max_length=20)),
                ('total_data_volume', models.CharField(help_text='Total data volume in bundle', max_length=50)),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0.0, help_text='Discount percentage', max_digits=5)),
                ('description', models.TextField(blank=True)),
                ('features', models.JSONField(default=list, help_text='List of features included')),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bundles', to='store.serviceprovider')),
            ],
            options={
                'verbose_name': 'Bundle',
                'verbose_name_plural': 'Bundles',
                'ordering': ['-is_featured', 'total_price'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='bundle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.bundle'),
        ),
        migrations.CreateModel(
            name='DataPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('data_volume', models.CharField(help_text='e.g., 1GB, 500MB, Unlimited', max_length=50)),
                ('validity_days', models.IntegerField(default=1, help_text='Validity in days')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('data_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('special', 'Special Offer'), ('night', 'Night Bundle'), ('social', 'Social Media'), ('youtube', 'YouTube'), ('streaming', 'Streaming')], default='monthly', max_length=20)),
                ('network_type', models.CharField(choices=[('4g', '4G LTE'), ('5g', '5G'), ('3g', '3G'), ('2g', '2G')], default='4g', max_length=10)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_plans', to='store.serviceprovider')),
            ],
            options={
                'verbose_name': 'Data Plan',
                'verbose_name_plural': 'Data Plans',
                'ordering': ['provider', 'price'],
            },
        ),
        migrations.AddField(
            model_name='bundle',
            name='data_plans',
            field=models.ManyToManyField(blank=True, related_name='bundles', to='store.dataplan'),
        ),
        migrations.AddField(
            model_name='order',
            name='data_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.dataplan'),
        ),
        migrations.DeleteModel(
            name='DataBundle',
        ),
    ]
